version: '3'

services:
  app:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the path to your Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
